on:
  issues:
    types: [ opened ]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@0.9.0
        with:
          script: |
            let fs = require('fs')
            let path = require('path')
            let content = fs.readFileSync('.github/reply.template','utf8')
            content = content.replace(/\${handle}/g, () => `@${context.issue.user.owner}`)

            github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: content
            })
