on:
  issues:
    types: [ opened ]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'Workflow Consultation') 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@0.9.0
        with:
          script: |
            let fs = require('fs')
            console.log(JSON.stringify(context))
            console.log(context.payload.issue.user.login)
            let content = fs.readFileSync('.github/reply.template','utf8')
            content = content.replace(/\${handle}/g, () => `@${context.issue.owner}`)

            github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: content
            })
